### ISSUE TITLE
[feature] 冒险者科技官网-联系我们

### ISSUE THREAD

**Issue by Aimee-dai** [adventurer-tech/adventurer.tech#13]
## 用户故事
我需要联系这家公司

-----------------
### web
- 内容没有错误
### 移动端
- 按照设计稿展示内容

**Comment by Aimee-dai** [comment]
![image](https://user-images.githubusercontent.com/42869404/63211743-0b139580-c12e-11e9-8c7b-90c61dfb138d.png)

**Comment by Aimee-dai** [comment]
如何发过来？把信息发到那里去？放到GitHub上？

**Comment by Aimee-dai** [comment]
## 蓝湖
https://lanhuapp.com/url/6LJdq-kphB3

**Comment by zzswang** [comment]
发过来的信息 发到 企业微信上吧，企业微信机器人 可以研究一下，王韬有实现过，应该比较轻量的。
